apiVersion: apps/v1
kind: Deployment
metadata:
  name: gift
  labels:
    app: gift
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gift
  template:
    metadata:
      labels:
        app: gift
    spec:
      containers:
        - name: gift
          image: username/gift:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5